# Generated by Django 5.1.3 on 2024-11-29 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='trip',
            name='capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='trip.capital', verbose_name='Столица'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='trip.tagpost', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='trip',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='trip.topics', verbose_name='Тема'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-time_create'], name='trip_trip_time_cr_576370_idx'),
        ),
    ]
